import 'package:flutter/material.dart';
import 'package:quickcart/models/bagProduct.dart';

List<Product> allproducts = [
  Product(
      id: 1,
      title: "Office Code",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/bag_1.png",
      color: Color(0xFF3D82AE)),
  Product(
      id: 2,
      title: "Belt Bag",
      price: 234,
      size: 8,
      description: dummyText,
      image: "assets/images/bag_2.png",
      color: Color(0xFFD3A984)),
  Product(
      id: 3,
      title: "Hang Top",
      price: 234,
      size: 10,
      description: dummyText,
      image: "assets/images/bag_3.png",
      color: Color(0xFF989493)),
  Product(
      id: 1,
      title: "Office Code",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/bag_1.png",
      color: Color(0xFF3D82AE)),
  Product(
      id: 2,
      title: "Belt Bag",
      price: 234,
      size: 8,
      description: dummyText,
      image: "assets/images/dress/dress_2.png",
      color: const Color(0xFFD3A984)),
  Product(
      id: 3,
      title: "Hang Top",
      price: 234,
      size: 10,
      description: dummyText,
      image: "assets/images/dress/dress_3.png",
      color: const Color(0xFF989493)),
  Product(
      id: 4,
      title: "Old Fashion",
      price: 234,
      size: 11,
      description: dummyText,
      image: "assets/images/dress/dress_4.png",
      color: const Color(0xFFE6B398)),
  Product(
      id: 5,
      title: "Office Code",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/dress/dress_5.png",
      color: const Color(0xFFFB7883)),
  Product(
    id: 6,
    title: "Office Code",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/images/dress/dress_6.png",
    color: const Color(0xFFAEAEAE),
  ),
  Product(
      id: 2,
      title: "Belt Bag",
      price: 234,
      size: 8,
      description: dummyText,
      image: "assets/images/bag_2.png",
      color: Color(0xFFD3A984)),
  Product(
      id: 3,
      title: "Hang Top",
      price: 234,
      size: 10,
      description: dummyText,
      image: "assets/images/bag_3.png",
      color: Color(0xFF989493)),
  Product(
      id: 4,
      title: "Old Fashion",
      price: 234,
      size: 11,
      description: dummyText,
      image: "assets/images/bag_4.png",
      color: Color(0xFFE6B398)),
  Product(
      id: 5,
      title: "Office Code",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/bag_5.png",
      color: Color(0xFFFB7883)),
  Product(
    id: 6,
    title: "Office Code",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_6.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
      id: 4,
      title: "Old Fashion",
      price: 234,
      size: 11,
      description: dummyText,
      image: "assets/images/bag_4.png",
      color: Color(0xFFE6B398)),
  Product(
      id: 5,
      title: "Office Code",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/bag_5.png",
      color: Color(0xFFFB7883)),
  Product(
    id: 6,
    title: "Office Code",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_6.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
      id: 1,
      title: "Classic Formal",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/shoes/shoe_1.png",
      color: const Color(0xFFD3A984)),
  Product(
      id: 2,
      title: "Leather Loafers",
      price: 234,
      size: 8,
      description: dummyText,
      image: "assets/images/shoes/shoe_2.png",
      color: const Color(0xFF3D82AE)),
  Product(
      id: 3,
      title: "Sporty Sneakers",
      price: 234,
      size: 10,
      description: dummyText,
      image: "assets/images/shoes/shoe_3.png",
      color: const Color(0xFF989493)),
  Product(
      id: 4,
      title: "Vintage Style",
      price: 234,
      size: 11,
      description: dummyText,
      image: "assets/images/shoes/shoe_4.png",
      color: const Color(0xFFE6B398)),
  Product(
      id: 5,
      title: "Elegant Oxfords",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/shoes/shoe_5.png",
      color: const Color(0xFFFB7883)),
  Product(
    id: 6,
    title: "Casual Canvas",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/images/shoes/shoe_6.png",
    color: const Color(0xFFAEAEAE),
  ),
  Product(
      id: 1,
      title: "Diamond Necklace",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/jewelleries/jewellery_1.png",
      color: const Color(0xFF3D82AE)),
  Product(
      id: 2,
      title: "Gold Bracelet",
      price: 234,
      size: 8,
      description: dummyText,
      image: "assets/images/jewelleries/jewellery_2.png",
      color: const Color(0xFFD3A984)),
  Product(
      id: 3,
      title: "Silver Earrings",
      price: 234,
      size: 10,
      description: dummyText,
      image: "assets/images/jewelleries/jewellery_3.png",
      color: const Color(0xFF989493)),
  Product(
      id: 4,
      title: "Emerald Ring",
      price: 234,
      size: 11,
      description: dummyText,
      image: "assets/images/jewelleries/jewellery_4.png",
      color: const Color(0xFFE6B398)),
  Product(
      id: 5,
      title: "Pearl Pendant",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/jewelleries/jewellery_5.png",
      color: const Color(0xFFFB7883)),
];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";
